version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_DB: cashflow_db
      POSTGRES_USER: cashflow_user
      POSTGRES_PASSWORD: cashflow_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./development/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./development/backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://cashflow_user:cashflow_password@postgres:5432/cashflow_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - ENVIRONMENT=development
    depends_on:
      - postgres
      - redis
    volumes:
      - ./development/backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./development/frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./development/frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:
